'use strict';
const examples={
 solicitud:{request:"I'd like an estimate to repaint my living room and two bedrooms.",reply:'Thanks for reaching out about your painting project. What ZIP code is the property in, and when would you like the work done? Our team will follow up to discuss an estimate.',title:'La consulta queda registrada.',service:'Sala + 2 recámaras',status:'Consulta recibida · Contacto TEST',next:'Revisar zona y contactar al propietario',note:'Tienes la información para retomar el contacto, aunque estés en la obra.'},
 filtro:{request:'My ZIP code is 78209. I would like to discuss an estimate for next month.',reply:'Thank you. Our painting team will review your location and project details before confirming an estimate visit.',title:'Datos para decidir si encaja.',service:'Pintura interior · San Antonio',status:'Datos TEST · ZIP 78209 · Próximo mes',next:'Confirmar cobertura y acordar una visita',note:'El contratista confirma disponibilidad. Todavía no hay una cita ni una venta.'},
 seguimiento:{request:'I would like an estimate, but I have not picked a date yet.',reply:'Are you still interested in an estimate? Let us know a convenient time for our painting team to contact you.',title:'El pendiente sigue visible.',service:'Solicitud de pintura interior',status:'Ejemplo de recordatorio si no responde',next:'Atender la respuesta y confirmar el siguiente paso',note:'El recordatorio se detiene cuando responde. Tu equipo atiende la conversación.'}
};
const beforeExamples={
 solicitud:{request:examples.solicitud.request,reply:'Respuesta pendiente',title:'El mensaje llega. El pendiente no queda asignado.',service:'Sala + 2 recámaras',status:'Consulta sin registrar en un seguimiento',next:'Depende de que recuerdes volver al mensaje',note:'Ejemplo de un proceso desorganizado. No sabemos si así trabaja tu negocio.'},
 filtro:{request:examples.solicitud.request,reply:'ZIP y fecha todavía sin preguntar',title:'Todavía faltan datos para decidir.',service:'Solicitud de pintura interior',status:'Cobertura y fecha sin confirmar',next:'Volver a buscar la conversación y pedir los datos',note:'Antes de acordar una visita, necesitas saber dónde está la propiedad y para cuándo quiere el trabajo.'},
 seguimiento:{request:examples.seguimiento.request,reply:'Sin recordatorio preparado',title:'La conversación queda en el aire.',service:'Solicitud de pintura interior',status:'Sin un siguiente paso registrado',next:'Recordar a quién falta responder',note:'Este escenario no significa que la venta esté perdida. Muestra un pendiente sin organizar.'}
};
let demoMode='after',currentStage='solicitud';
function selectStage(stage){if(!examples[stage])return false;currentStage=stage;const ex=(demoMode==='before'?beforeExamples:examples)[stage];const ids={'customer-message':'request','business-message':'reply','owner-title':'title','service-result':'service','status-result':'status','next-result':'next','owner-note':'note'};for(const[id,key]of Object.entries(ids)){const el=document.getElementById(id);if(el)el.textContent=ex[key];}document.querySelectorAll('[data-stage]').forEach(b=>{const active=b.dataset.stage===stage;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('[data-track]').forEach(el=>el.classList.toggle('current',demoMode==='after'&&el.dataset.track===stage));const reply=document.getElementById('business-message');if(reply)reply.lang=demoMode==='before'?'es':'en';return true;}
function selectMode(mode){if(!['before','after'].includes(mode))return false;demoMode=mode;document.querySelector('.demo-shell')?.classList.toggle('is-before',mode==='before');document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});document.getElementById('demo-context').textContent=mode==='before'?'Antes: un ejemplo de consultas que dependen de tu memoria y de mensajes sueltos.':'Con Chori-SEO: la consulta se registra y el pendiente queda visible para tu equipo.';document.getElementById('demo-message-note').textContent=mode==='before'?'Escenario ilustrativo: el texto gris indica lo que falta; no es un mensaje enviado.':'Ejemplo de mensaje inicial; se adapta y aprueba durante el montaje.';selectStage(currentStage);return true;}
document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>selectStage(b.dataset.stage)));
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>selectMode(b.dataset.mode)));
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
function calculateBreakEven(contribution,ads,fee=850){if(!Number.isFinite(contribution)||!Number.isFinite(ads)||!Number.isFinite(fee)||contribution<=0||contribution>1000000||ads<0||ads>1000000||fee!==850)return null;const investment=fee+ads;return{investment,jobs:Math.ceil(investment/contribution)};}
const contributionInput=document.getElementById('contribution'),adInput=document.getElementById('ad-spend'),calcPlan=document.getElementById('calc-plan');
function updateCalculator(){if(!contributionInput||!adInput )return;const result=calculateBreakEven(contributionInput.valueAsNumber,adInput.valueAsNumber,850);document.getElementById('calc-investment').textContent=result?money.format(result.investment):'—';document.getElementById('calc-jobs').textContent=result?String(result.jobs):'—';document.getElementById('calc-description').textContent=result?(result.jobs===1?'trabajo adicional cobrado':'trabajos adicionales cobrados'):'Introduce un margen mayor que cero y un presupuesto válido.';}
[contributionInput,adInput,calcPlan].filter(Boolean).forEach(el=>el.addEventListener('input',updateCalculator));updateCalculator();
let selectedPlan='';const planLabels={mensual:'Mensual · $850 USD/mes'};
function selectPlan(plan){if(!Object.hasOwn(planLabels,plan))return false;selectedPlan=plan;const label=document.getElementById('chosen-plan');if(label)label.textContent='Plan de interés: '+planLabels[plan];return true;}
document.querySelectorAll('[data-plan]').forEach(el=>el.addEventListener('click',()=>selectPlan(el.dataset.plan)));
const mobileCta=document.querySelector('.mobile-cta'),evaluationSection=document.getElementById('evaluar');if(mobileCta&&evaluationSection&&'IntersectionObserver'in window){new IntersectionObserver(entries=>{entries.forEach(entry=>{mobileCta.classList.toggle('obscured',entry.isIntersecting);mobileCta.inert=entry.isIntersecting;});},{threshold:0}).observe(evaluationSection);}
// Feature-detected local demo tool, retained from the existing site.
if(document.modelContext?.registerTool){const lifetime=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'show_painting_conversation_example',title:'Ver una etapa del seguimiento de pintura',description:'Muestra una etapa de la demostración visible. No envía mensajes, agenda visitas ni guarda información.',inputSchema:{type:'object',properties:{stage:{type:'string',enum:Object.keys(examples)}},required:['stage'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(key=>key!=='stage')||!Object.hasOwn(examples,input.stage))throw new Error('Etapa no válida');selectMode('after');selectStage(input.stage);return{stage:input.stage,...examples[input.stage],simulated:true};}},{signal:lifetime.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});}catch{}}
